Listener scope
stackabletech/secret-operator pull request #310
Opened 2023-08-29 16:33 UTC by nightkr

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2023-10-19 14:39 UTC, siegfriedweber requested changes

2023-10-19 15:04 UTC, nightkr commented on deploy/helm/secret-operator/templates/daemonset.yaml
> +              value: /csi-listop/csi.sock
Good catch, legacy leftover. We used to query listop directly before `PodListeners` was added.

2023-10-19 15:06 UTC, nightkr commented on rust/operator-binary/src/backend/pod_info.rs
> +                        .context(GetListenerVolumeSnafu { listener_volume })?,
We don't necessarily know the `storageClassName`. We preinstall one named `listeners.stackable.tech` (and assume it exists), but technically any SC with `StorageClass.provisioner: listeners.stackable.tech` would work.

2023-10-20 06:39 UTC, siegfriedweber commented on rust/operator-binary/src/backend/pod_info.rs
> +                        .context(GetListenerVolumeSnafu { listener_volume })?,
Okay, then let's leave it as it is.

2023-10-26 10:24 UTC, nightkr commented on deploy/helm/secret-operator/templates/daemonset.yaml
> +              value: /csi-listop/csi.sock
ebcda1af8811b53cb26b5c8ccd762b8a5ff87854

2023-10-26 10:53 UTC, nightkr commented on Cargo.toml
> +stackable-operator = { git = "https://github.com/stackabletech//operator-rs.git", branch = "feature/podlisteners" }
9ad9cfc083caab3a02d9b2398cf7b4729673b808

2023-10-26 10:53 UTC, nightkr commented on CHANGELOG.md
> +- `operator-rs` `0.44.0` -> `0.48.0` ([#310]).
9ad9cfc083caab3a02d9b2398cf7b4729673b808

2023-10-26 11:11 UTC, nightkr commented on docs/modules/secret-operator/pages/scope.adoc
e7f11e033fa4ad919e4dcb842b559ace544ddf87

2023-11-06 09:46 UTC, siegfriedweber commented
Waiting for https://github.com/stackabletech/listener-operator/pull/100#discussion_r1323254091 to be resolved. But otherwise LGTM.

2023-11-06 13:26 UTC, siegfriedweber approved these changes
LGTM

2023-11-06 13:35 UTC, merged