feat(helm): support labels in values.yaml
stackabletech/secret-operator pull request #352
Opened 2024-01-26 14:16 UTC by razvan

Part of: https://github.com/stackabletech/issues/issues/501

2024-01-29 09:49 UTC, Techassi requested changes

2024-01-29 09:49 UTC, Techassi commented on deploy/helm/secret-operator/templates/roles.yaml
note: Seems like we can include the labels in many more templated resources, like `SecretClass` and `StorageClass`.

2024-01-29 09:49 UTC, Techassi commented on deploy/helm/secret-operator/values.yaml
> +  pullSecrets: []
nit: Add a newline to separate these two blocks.

2024-01-29 11:54 UTC, razvan commented on deploy/helm/secret-operator/templates/roles.yaml
Shouldn't we?

2024-01-29 12:57 UTC, razvan commented on deploy/helm/secret-operator/templates/roles.yaml
sorry. now I got what you meant. [Done](https://github.com/stackabletech/secret-operator/pull/352/commits/6a4c70067aa4cd347fa574cc42dff0c6b2bf20de)

2024-01-29 13:08 UTC, Techassi submitted a review, later dismissed

2024-01-30 08:31 UTC, Techassi approved these changes

2024-01-30 08:35 UTC, merged